### ISSUE TITLE
ClassCondFlow example missing

### ISSUE THREAD

**Issue by maulberto3** [VincentStimper/normalizing-flows#18]
Would be great to see an example for the conditional class. Will try to create one.

**Comment by VincentStimper** [comment]
Hi @maulberto3,

there is a script for training a class conditional Glow model build with `normflows` on images in [another repository](https://github.com/VincentStimper/resampled-base-flows/blob/master/experiments/train_glow.py) of mine. 

Best regards,
Vincent
