### ISSUE TITLE
Reverse using z

### ISSUE THREAD

**Issue by dgjung0220** [VincentStimper/normalizing-flows#21]
Hi, thanks for the code!
This code is learning a lot for me.

But besides  sampling from the distribution, 
I wonder how to implement reverse using latent z. (reverse flow)

**Comment by VincentStimper** [comment]
Hi @dgjung0220,

You could build a [composite flow](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/flows/base.py#L48) from a list of flow layers and then use the forward and inverse method of it.
I agree that this is a bit cumbersome, there should be a forward and an inverse method in the [flow module](https://github.com/VincentStimper/normalizing-flows/blob/master/normflows/core.py#L9) itself. I'm going to implement this within the next days and let you know once it is finished.

Best regards,
Vincent

**Comment by dgjung0220** [comment]
Wow, if It is implemented, it would be easier to experiment something with your code. Thank you.

**Comment by VincentStimper** [comment]
Hi @dgjung0220,

I added a `forward` and `inverse` method to the flow model in my [development branch](https://github.com/VincentStimper/normalizing-flows/tree/dev-vs). You can clone the branch and install this version of the package via
```
pip install --upgrade .
```
I tested it briefly, so it should be save to use, but I'll wait with closing this issue until I merge the changes to master.

Best regards,
Vincent

**Comment by VincentStimper** [comment]
The changes are now on `master` and will be part of the version on PyPI as soon as there is a new release.
