### ISSUE TITLE
Categorical Input Features?

### ISSUE THREAD

**Issue by fountaindive** [VincentStimper/normalizing-flows#25]
Hi,

I was wondering if you package can support a dataset with input continuous and categorical features.

Many thanks!

**Comment by abao1999** [comment]
Along those lines, how would I be able to use this for tabular data, or say to transform a 4D Gaussian base distribution into some arbitrary 4D density?

**Comment by bmurders2** [comment]
Unfortunately, normalizing flows doesn't handle categorical inputs as there's no intrinsic distribution to approximate. However, and I haven't implemented this approach yet, you could attempt to train an autoencoder to map all input features (including categorical) to a latent space that is continuous and use one of the methods for normalizing flows (e.g., real NVP) to learn that latent space's distributions. Then use the decoder on the normalizing flow model's output to get the "original" output values. You can Google "categorical normalizing flows" for more information.

**Comment by fountaindive** [comment]
Many thanks for replying to my old comment! Yeah that are some interesting articles on 'categorical normalizing flows'.
