### ISSUE TITLE
No community contribution guideline

### ISSUE THREAD

**Issue by kazewong** [VincentStimper/normalizing-flows#30]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5361

Currently, there is no community contribution guideline I can find. Per Joss review checklist:

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

There should be a standard template, it would be good to have an explicit contribution guide in the root directory

**Comment by VincentStimper** [comment]
Hi @kazewong,

given that this is a GitHub repository, I thought it would be self-explanatory that you can get help by submitting an issue and contribute via PRs. However, I agree that a guideline will help in any case.
Hence, [I added](https://github.com/VincentStimper/normalizing-flows/commit/2eb6cb2b1a46835876e219363d685316442acf2b) a guideline for getting support and contributing to the package to the [README](https://github.com/VincentStimper/normalizing-flows/blob/master/README.md).

Please let me know whether this is sufficient.

Best regards,
Vincent

**Comment by kazewong** [comment]
Looks good to me. Thanks for adding this.
