### ISSUE TITLE
Putting examples in the documentation 

### ISSUE THREAD

**Issue by kazewong** [VincentStimper/normalizing-flows#35]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5361

The examples in the repo are currently hosted under the https://github.com/VincentStimper/normalizing-flows/tree/master/examples folder. I think it would be nice to add a page in the documentation site that display these ipython notebook https://vincentstimper.github.io/normalizing-flows/, just like the API page.

Note that this issue is a nice to have that I don't think is necessary for JOSS review, so it shouldn't block the review process.

**Comment by VincentStimper** [comment]
Hi @kazewong,

good idea, I'm just wondering how to realize this. We could just add a table to the README with links to all the notebooks. 
Other than that, is there a way to show the example notebooks in the documentation, @vincentberenz?

Best regards,
Vincent

**Comment by vincentberenz** [comment]
@VincentStimper 
There are two ways of doing this.

## mkdocs-jupyter
See: https://github.com/danielfrg/mkdocs-jupyter
This allows to add a visual html representation of the notebook in the documentation.
pros: We just need to setup the configuration of mkdocs once, and then things will be updated automatically every time a notebook is modified (or added, or deleted)
cons: This looks nice, but no code can be executed.
effort: I will need to find out how to make a nice layout in the menu, should not be too hard

## jupyter-cloud.gwdg.de
See: https://jupyter-cloud.gwdg.de
This is a server on which MPI employees can upload (and make public) notebook.
So we can upload the notebooks there, and provide a page in the documentation linking to them
pros: Code can be executed
cons: We need to reupload manually the notebooks everytime we update them
effort: A bit unclear how to make things public, and if dependencies package can be installed for each user. 

Let me know which solution you would prefer

**Comment by VincentStimper** [comment]
Hi @vincentberenz,

I don't think the notebooks have to be executable. For this purpose, we already have the Google Colab notebooks. Hence, the first solution sounds just right to me. 

Can we leave the notebooks in the current folder outside the package folder? It would be great if you had a look at how to make a nice layout.

Best regards,
Vincent

**Comment by VincentStimper** [comment]
Hi @kazewong,

@vincentberenz has added this feature, thanks a lot!
You're welcome to have a look at the [current documentation](https://vincentstimper.github.io/normalizing-flows/) yourself and close the issue if this is what you had in mind. 

Best regards,
Vincent
