### ISSUE TITLE
Conditional Flows implementation / documentation

### ISSUE THREAD

**Issue by cranmer** [VincentStimper/normalizing-flows#41]
Hello, it's not clear to me if this package implements a conditional flow $p(x| u)$ where $u$ is continuous (i.e. $u \in \mathbb{R}^n$) as opposed to a discrete class label.

If so, could you please point me to an example if you have one? 
If it is implemented, I would also suggest some tweaks  to documentation to make that more clear.

Thanks for the nice package!

**Comment by VincentStimper** [comment]
Hi Prof. @cranmer,

there existed some support for flows conditioned on continuous variables scattered around the package, but it was incomplete and, indeed, not very well documented.

I added some functionality now, such as a [`ConditionalNormalizingFlow`](https://github.com/VincentStimper/normalizing-flows/blob/d57b6b78d976389fb1ec9d563136820172a74e42/normflows/core.py#L216) model class, a [`ConditionalDiagGaussian`](https://github.com/VincentStimper/normalizing-flows/blob/d57b6b78d976389fb1ec9d563136820172a74e42/normflows/distributions/base.py#L106) base distribution, where the parameters are encoded by the conditional, and a few flows support now conditional variables. An example for a conditional MAF and a conditional autoregressive NSF is given [here](https://github.com/VincentStimper/normalizing-flows/blob/master/examples/conditional_flow.ipynb); it is also in the [documentation](https://vincentstimper.github.io/normalizing-flows/examples/conditional_flow/).

If there is any particular flow besides those implemented that you want to use with continuous conditional variables, please let me know.

Best regards,
Vincent

**Comment by VincentStimper** [comment]
The changes are part of the new version of the package I just released on [PyPI](https://pypi.org/project/normflows/). Hence, I'll close this issue. If there are still more features you wish to be included, please create a new issue.
