### ISSUE TITLE
Remove Lambda's

### ISSUE THREAD

**Issue by gianmarcoaversanoenx** [VincentStimper/normalizing-flows#43]
In the MADE class, there is the `preprocessing` attribute created as lambda. Please remove this or it will be impossible to `torch.save()`.

**Comment by VincentStimper** [comment]
Hi @gianmarcoaversanoenx,

I tried to reproduce the error you are describing, but for me saving and loading of models with MADE nets works fine with `model.save` and `model.load` no matter if `preprocessing` is a lambda function or not. 
Can you provide a code snippet to reproduce this error, please?

Best regards,
Vincent

**Comment by gianmarcoaversanoenx** [comment]
```python
n_flos: int
dim: int
n_layers: int
hidden_units: int
for _ in range(n_flows):
                flows += [
                    normflows.flows.AutoregressiveRationalQuadraticSpline(
                        dim,
                        n_layers,
                        hidden_units,
                    )
                ]
                flows += [normflows.flows.LULinearPermute(dim)]
# Set base distribution
base = normflows.distributions.DiagGaussian(dim, trainable=False)
# Build flow model
nf = normflows.NormalizingFlow(base, flows)

# Save
torch.save(nf, 'model.ckpt`)
```

This would give me: `Can't pickle MADE.<local>(lambda)...```

**Comment by VincentStimper** [comment]
Hi @gianmarcoaversanoenx,

thanks, I could reproduce the error now and replaced the lambda functions with something that can be pickled. Feel free to try it out yourself by installing the package from the current master branch.

Best regards,
Vincent

**Comment by gianmarcoaversanoenx** [comment]
Thanks! :) Is this going to be pushed to PyPI, too?

**Comment by VincentStimper** [comment]
Hi @gianmarcoaversanoenx,

sure, I will do so in about 1-2 weeks.

Best regards,
Vincent

**Comment by VincentStimper** [comment]
I just released a new version of the package on [PyPI](https://pypi.org/project/normflows/). Hence, I'll close this issue.
