### ISSUE TITLE
Could you give an example for NICE?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [VincentStimper/normalizing-flows#48]
@VincentStimper 
Awesome repo. Thanks
I want to work on NICE. Didn't find the NICE example here. Could you give NICE example?

**Comment by VincentStimper** [comment]
Hi @AI-ML-Enthusiast,

NICE is simply Real NVP but without the scale in the affine map, so you can follow the [Real NVP example](https://github.com/VincentStimper/normalizing-flows/blob/master/examples/real_nvp_colab.ipynb) and set the `scale` argument in the  [`AffineCouplingBlock`](https://github.com/VincentStimper/normalizing-flows/blob/d1a6af7b15bf0245f1bc4c18e1694541872b29d8/normflows/flows/affine/coupling.py#L232) to `False`. Note that this reduces the number of parameters by a factor of two, so in the example notebook you have to change the network outputting the parameters to
```
param_map = nf.nets.MLP([1, 64, 64, 1], init_zeros=True)
```

Best regards,
Vincent
