### ISSUE TITLE
NICE demo?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [VincentStimper/normalizing-flows#49]
Thanks for your awesome repo.
Could you provide NICE demo?

**Comment by VincentStimper** [comment]
Hi @AI-ML-Enthusiast,

I already addressed this in [this issue](https://github.com/VincentStimper/normalizing-flows/issues/48). Note that NICE is also part of [this example](https://github.com/VincentStimper/normalizing-flows/blob/master/examples/comparison_plan_rad_aff.ipynb).

Best regards,
Vincent
