### ISSUE TITLE
What dou you mean by "Augmented Normalizing Flow based on Real NVP"?

### ISSUE THREAD

**Issue by fzy28** [VincentStimper/normalizing-flows#50]
Nice work! 
But I am a bit confused about your implementation in the examples, "augmented_flow.ipynb".
I wonder what do you mean "Augmented Normalizing Flow" and the "Set augmented target"?
```
# Set augmented target
target = nf.distributions.TwoIndependent(nf.distributions.TwoMoons(), 
                                         nf.distributions.DiagGaussian(2))
```
Is there some reference for further explanation about why it works?
Thanks!

**Comment by VincentStimper** [comment]
Hi @fzy28,

in the notebook, an augmented normalizing flow introduced in [this paper](https://arxiv.org/abs/2002.07101) is implemented. Auxiliary dimensions are added to increase expressivity and a Gaussian target distribution is used for them. On inference, they are marginalized out to obtain a distribution for the random variable of interest.

Best regards,
Vincent
