### ISSUE TITLE
Plotting Code in flow_plot does not work

### ISSUE THREAD

**Issue by plehman2000** [VincentStimper/normalizing-flows#6]

**Comment by VincentStimper** [comment]
Hi @plehman2000,
thanks for the hint! The notebook was indeed outdated. I updated and renamed it and now it should work:
https://github.com/VincentStimper/normalizing-flows/blob/master/example/comparison_plan_rad_aff.ipynb
Let me know if you still experience any problems.
Best regards,
Vincent
