### ISSUE TITLE
Documentation clarification of forward_kld

### ISSUE THREAD

**Issue by adam2392** [VincentStimper/normalizing-flows#64]
https://vincentstimper.github.io/normalizing-flows/references/#normflows.flows does not have an entry for `y` in the forward-kid function  even though it is an input argument for `forward_kld`. 

I was wondering what the description of `y` should be in this method? In `log_prob(x, y)`, it specifies that `y` is the class. Is this the case? So given say a dataset of `(X, y)`, we feed in batches of X and class labels y and want to minimize the KL divergence between the decoded `\hat{X}` and input X over each class label distribution?

**Comment by VincentStimper** [comment]
Hi @adam2392,

The documentation is indeed not clear there, thanks for pointing this out. In this case, `y` is the class in case the model is class-conditional. I clarified this in [this commit](https://github.com/VincentStimper/normalizing-flows/commit/c6616b1a9f04c0e894b9e045e66bd504db17ef5e).

Best regards,
Vincent
